#server
server:
  port: 9696

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobhub
    username: sumit8669
    password: Bitudb2628
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect




#H2
#spring:
#  application:
#    name: jobhub
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

#Actuator
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true
#  info:
#    env:
#      enabled: true
#
#info:
#  app:
#  name: 'Job Application'
#  description: 'Job app build by sumit rana'
#  version: 1.0.0
