#spring.application.name=jobhub
server:
  port: 9696
spring:
  application:
    name: jobhub
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true