#spring.application.name=jobhub
server:
  port: 9696
spring:
  application:
    name: jobhub
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: 'Job Application'
    description: 'Job app build by sumit rana'
    version: 1.0.0
