server:
  port: 9093

#PostgreSQL
spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5432/review
    username: sumit8669
    password: Bitudb2628
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/