server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: sumit8669
    password: Bitudb2628
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect