server:
  port: 9092

#PostgresSQL
spring:
  application:
    name: job-sevice
  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: sumit8669
    password: Bitudb2628
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Zipkin
management:
  tracing:
    sampling:
      probability: 1.0